import { IsString, IsOptional, IsIn, IsNotEmpty } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class RegisterDeviceDto {
  @ApiProperty({ description: 'Device id generated by client (unique)' })
  @IsString()
  @IsNotEmpty()
  deviceId: string;

  @ApiProperty({ example: 'ios' })
  @IsString()
  @IsIn(['ios', 'android', 'web'])
  platform: string;

  @ApiPropertyOptional({ description: 'Push token (FCM/APNs)' })
  @IsOptional()
  @IsString()
  pushToken?: string | null;

  @ApiPropertyOptional({ description: 'Device model, e.g. iPhone 14' })
  @IsOptional()
  @IsString()
  deviceModel?: string | null;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  osVersion?: string | null;

  @ApiPropertyOptional()
  @IsOptional()
  @IsString()
  appVersion?: string | null;
}
